sudo: false
addons:
  apt:
    packages:
      - aspell
language: perl
perl:
  - blead       # builds perl from git
  - dev         # latest point release
  - "5.26.1"
  - "5.24.3"
  - "5.22.4"
  - "5.20.3"
  - "5.18.4"
  - "5.16.3"
  - "5.14.4"
  - "5.12.5"
  - "5.10.1"
matrix:
  allow_failures:
    # - perl: blead
    - perl: "5.12"
    - perl: "5.10"
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - perl -M5.014 -e1 2>/dev/null || cpan-install Dist::Zilla@5.047
  - cpan-install --deps
script:
  - perl Build.PL
  - ./Build
  - prove -b -r -s -j1 $(test-files)
